### ISSUE TITLE
ERROR:gpodder.download:Download failed: 'bool' object is not iterable

### ISSUE THREAD

**Issue by schmittlauch** [gpodder/gpodder-sailfish#211]
Some certain episodes fail to download in gpodder-sailfish-4.17.1:

```
[D] unknown:0 - Using Wayland-EGL
library "libui_compat_layer.so" not found
library "libutils.so" not found
library "libcutils.so" not found
library "libhardware.so" not found
library "android.hardware.graphics.mapper@2.0.so" not found
library "android.hardware.graphics.mapper@2.1.so" not found
library "android.hardware.graphics.mapper@3.0.so" not found
library "android.hardware.graphics.mapper@4.0.so" not found
library "libc++.so" not found
library "libhidlbase.so" not found
library "libgralloctypes.so" not found
library "android.hardware.graphics.common@1.2.so" not found
library "libion.so" not found
library "libz.so" not found
library "libhidlmemory.so" not found
library "android.hidl.memory@1.0.so" not found
library "vendor.qti.qspmhal@1.0.so" not found
[D] unknown:0 - Got library name:  "/usr/lib64/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
[W] unknown:51 - file:///usr/share/harbour-org.gpodder.sailfish/qml/common/GPodderPlayback.qml:51:38: QML Connections: Cannot assign to non-existent property "onAudioBecomingNoisy"
[W] unknown:42 - file:///usr/share/harbour-org.gpodder.sailfish/qml/CoverContainer.qml:42:5: QML Column: Cannot specify top, bottom, verticalCenter, fill or centerIn anchors for items inside Column. Column will not function.
[D] onCompleted:580 - Warning: specifying an object instance for initialPage is sub-optimal - prefer to use a Component
[W] unknown:48 - file:///usr/share/harbour-org.gpodder.sailfish/qml/CoverContainer.qml:48:37: Unable to assign [undefined] to QString
[W] unknown:52 - file:///usr/share/harbour-org.gpodder.sailfish/qml/common/GPodderPlayback.qml:52: ReferenceError: platform is not defined
[D] :53 - gPodder Core 4.17.1
[D] :54 - gPodder QML UI 4.17.1
[D] :55 - Podcastparser 0.6.6
[D] :56 - PyOtherSide 1.5.9
[D] :57 - Python 3.8.18
/usr/share/harbour-org.gpodder.sailfish/minidb.py:144: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (exc_type, exc_value, traceback) is (None, None, None):
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/_ohm_ – monoxyd/ohmlogo.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/_ohm_ – monoxyd/ohmlogo_3000.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Akronymisierbar/1516569434artwork.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/All Points North/13-1-4355773-1596006876350.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/All Points North/39-118267065201f1615336.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Extrem rechts – Der Hass-Händler und der Staat/extrem-rechts-100-podcastLogo_i-itunes_version-38770_zc-015d0843.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Extrem rechts – Der Hass-Händler und der Staat/extrem-rechts-100-podcastLogo_i-itunes_version-47494_zc-8676d24b.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Extrem rechts – Der Hass-Händler und der Staat/extrem-rechts-100-podcastLogo_i-itunes_version-12348_zc-c7fc79a4.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Haken dran – das Twitter-Update/34197316-1690224724518-7a9ded70dbcb5.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Haken dran – das Twitter-Update/34197316-1701631704844-cdb77fea41fbe.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Krieg in Europa – das Update zur Lage in der Ukraine/podcastbild412_v-quadratxl.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Krieg in Europa – das Update zur Lage in der Ukraine/podcastbild234_v-quadratxl.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Krieg in Europa – das Update zur Lage in der Ukraine/alsinwar102_v-quadratl.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Krieg in Europa – das Update zur Lage in der Ukraine/ukraine1822_v-quadratl.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Krieg in Europa – das Update zur Lage in der Ukraine/peskow104_v-quadratl.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Met _ Moshpit_ Der Mittelalter-Rock Podcast bei RADIO BOB_/9ae931fb-6173-43b3-8c63-aa8714d1c0ff.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Mission Klima – Lösungen für die Krise/esbjerg106_v-quadratxl.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Planet B _ Ideen für den Neuanfang/plb3000.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Rechtsbelehrung - Recht, Technik _ Gesellschaft/rechtsbelehrung-logo-3000x3000-10jahre.png
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Klimazentrale - Der Talk zu Klima _ Umwelt/1687506855051,sharing-economy-fuehrt-teilen-zu-mehr-nachhaltigkeit-102~_v-1x1@2dXL_-1f32c27c4978132dd0854e53b5ed30e10facc189.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Klimazentrale - Der Talk zu Klima _ Umwelt/1688707491264,wasser-bleibt-die-leitung-bald-trocken-102~_v-1x1@2dXL_-1f32c27c4978132dd0854e53b5ed30e10facc189.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Klimazentrale - Der Talk zu Klima _ Umwelt/1689918242015,photovoltaik-wie-steht-es-um-die-solarenergie-102~_v-1x1@2dXL_-1f32c27c4978132dd0854e53b5ed30e10facc189.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Klimazentrale - Der Talk zu Klima _ Umwelt/1691057868116,landwirtschaft-wie-sichern-wir-die-ernaehrung-102~_v-1x1@2dXL_-1f32c27c4978132dd0854e53b5ed30e10facc189.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Streitkräfte und Strategien _Ukraine/mediathekbild648_v-quadratxl.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Streitkräfte und Strategien _Ukraine/nato490_v-quadratxl.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Streitkräfte und Strategien _Ukraine/mediathekbild572_v-quadratxl.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Streitkräfte und Strategien _Ukraine/atompilz100_v-podcast.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Streitkräfte und Strategien _Ukraine/baltops114_v-quadratxl.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Tech Won_t Save Us/5cfec01b44f3e29fae1fb88ade93fc4aecd05b192fbfbc2c2f1daa412b7c1921.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Tech Won_t Save Us/e70382d1824eed07bf51f8b9742413cd1ad490e9f893e8ff33e49d552d3c73ea.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/The Haskell Interlude/f6fd9b4ca4e468e7e11c8350463c894b252ee834d352e0a8d889b97ac83aedef.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/The Haskell Interlude/60854458c4d1acdf4e1c2f79c4137142d85d78e379bdafbd69bd34c85f5819ad.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/WRINT_ Wer redet ist nicht tot/wrint_basis_weiss_400.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/You are fucked – Deutschlands erste Cyberkatastrophe/deutschlands-erste-cyberkatastrophe-hack-anhalt-bitterfeld-100-podcastLogo_i-itunes_version-52284_zc-aa6d4b54.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/You are fucked – Deutschlands erste Cyberkatastrophe/deutschlands-erste-cyberkatastrophe-hack-anhalt-bitterfeld-100-podcastLogo_i-itunes_version-27799_zc-91bce50e.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/You are fucked – Deutschlands erste Cyberkatastrophe/deutschlands-erste-cyberkatastrophe-hack-anhalt-bitterfeld-100-podcastLogo_i-itunes_version-31447_zc-fbb7d182.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/You are fucked – Deutschlands erste Cyberkatastrophe/deutschlands-erste-cyberkatastrophe-hack-anhalt-bitterfeld-100-podcastLogo_i-itunes_version-3695_zc-6c504f14.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/You are fucked – Deutschlands erste Cyberkatastrophe/deutschlands-erste-cyberkatastrophe-hack-anhalt-bitterfeld-100-podcastLogo_i-itunes_version-23530_zc-6fc323a4.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/You are fucked – Deutschlands erste Cyberkatastrophe/deutschlands-erste-cyberkatastrophe-hack-anhalt-bitterfeld-100-podcastLogo_i-itunes_version-25282_zc-1f5b0de1.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Die Fascho-Jägerin__ – Der Fall Lina E. und seine Folgen/die-faschojaegerin-linksextremismus-100-podcastLogo_i-itunes_version-10382_zc-c40577ff.jpg
WARNING:gpodder.model:Unknown external file: /home/defaultuser/.local/share/harbour-org.gpodder.sailfish/Die Fascho-Jägerin__ – Der Fall Lina E. und seine Folgen/die-faschojaegerin-linksextremismus-100-podcastLogo_i-itunes_version-52325_zc-2475c39a.jpg
WARNING:main:Config option changed: ui.qml.episode_list.filter_eql =  -> downloaded or downloading
[W] unknown:0 - libpng warning: iCCP: known incorrect sRGB profile
[W] unknown:0 - libpng warning: iCCP: known incorrect sRGB profile
ERROR:gpodder.download:Download failed: 'bool' object is not iterable
Traceback (most recent call last):
  File "/usr/share/harbour-org.gpodder.sailfish/gpodder/download.py", line 747, in run
    headers, real_url = downloader.retrieve_resume(url, self.tempname,
  File "/usr/share/harbour-org.gpodder.sailfish/gpodder/download.py", line 282, in retrieve_resume
    range = ContentRange.parse(headers.get('content-range', ''))
  File "/usr/share/harbour-org.gpodder.sailfish/gpodder/download.py", line 178, in parse
    return cls(start, end-1, length)
  File "/usr/share/harbour-org.gpodder.sailfish/gpodder/download.py", line 111, in __init__
    if not all(stop is None or (stop >= 0 and stop >= start)):
TypeError: 'bool' object is not iterable
ERROR:gpodder.download:Download failed: 'bool' object is not iterable
Traceback (most recent call last):
  File "/usr/share/harbour-org.gpodder.sailfish/gpodder/download.py", line 747, in run
    headers, real_url = downloader.retrieve_resume(url, self.tempname,
  File "/usr/share/harbour-org.gpodder.sailfish/gpodder/download.py", line 282, in retrieve_resume
    range = ContentRange.parse(headers.get('content-range', ''))
  File "/usr/share/harbour-org.gpodder.sailfish/gpodder/download.py", line 178, in parse
    return cls(start, end-1, length)
  File "/usr/share/harbour-org.gpodder.sailfish/gpodder/download.py", line 111, in __init__
    if not all(stop is None or (stop >= 0 and stop >= start)):
TypeError: 'bool' object is not iterable
INFO:gpodder.core:Shutting down core
INFO:gpodder.config:Flushing settings to disk
```

Streaming them works. 3 affected feeds are:
- https://detektor.fm/feeds/antritt
- https://wochendaemmerung.podigee.io/feed/opus
- https://www.ndr.de/nachrichten/info/podcast2998.xml

**Comment by Keeper-of-the-Keys** [comment]
Hey thanks for reporting!

Looks like I introduced a bug in gpodder-core, hope to have time to fix it this week.

**Comment by schmittlauch** [comment]
As this bug is triggered by resuming on an incompletely downloaded file, deleting that file in the filesystem is a workaround that makes the download succeed again.
