### ISSUE TITLE
Can't download episode 2017-10-23 from Netzpolitik Podcast

### ISSUE THREAD

**Issue by schmittlauch** [gpodder/gpodder-sailfish#55]
It' s not possible to download the episode *Gerhart Baum zu Bürgerrechten in der Jamaika-Koalition: „Es wird in jedem Fall besser.“*. Other episodes can be downloaded though and streaming this particular episode still works.

I was able to reproduce this issue with a freshly installed gpodder in the SDK emulator.

Feed URI: https://netzpolitik.org/category/netzpolitik-podcast/feed

Traceback:

```
2017-10-25 15:57:56,543 [gpodder.util] DEBUG: run_in_background: <function run_in_background_thread.<locals>.wrapper.<locals>.<lambda> at 0x5f2624ac> (False)
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nemo/gpodder-sailfish/main.py", line 56, in <lambda>
    util.run_in_background(lambda: f(*args))
  File "/home/nemo/gpodder-sailfish/main.py", line 269, in download_episode
    episode.download(progress_callback)
  File "/home/nemo/gpodder-sailfish/gpodder/model.py", line 212, in download
    task = download.DownloadTask(self)
  File "/home/nemo/gpodder-sailfish/gpodder/download.py", line 566, in __init__
    assert episode.download_task is None
AssertionError
```

I try to take a look into this.

**Comment by sfbg** [comment]
Hard to test as the episode is not in the feed anymore.
